Lessons/accounts/urls.py
from django.urls import path

from .views import AccountLoginView, AccountLogoutView, AccountRegistrationView, AccountUpdateView

app_name = 'accounts'

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile_update/', AccountUpdateView.as_view(), name='profile_update'),
]

Lessons/courses/urls.py
from courses.views import CourseCreateView, CourseDeleteView, CourseUpdateView, CoursesListView

from django.urls import path

app_name = 'courses'

urlpatterns = [
    path('', CoursesListView.as_view(), name='list'),
    path('create/', CourseCreateView.as_view(), name='create'),
    path('update/<int:pk>/', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CourseDeleteView.as_view(), name='delete'),
]

Lessons/groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', GroupDeleteView.as_view(), name='delete'),
]

Lessons/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lessons/students/urls.py
from django.urls import path

from students.views import StudentCreateView, StudentDeleteView, StudentUpdateView, StudentsListView

app_name = 'students'

urlpatterns = [
    path('', StudentsListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('update/<int:pk>/', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete'),
    # path('create/', create_student, name='create'),
    # path('update/<int:pk>/', update_student, name='update'),
    # path('update/<int:pk>/', UpdateStudentView.update_object, name='update'),
    # path('delete/<int:pk>/', delete_student, name='delete'),
]

Lessons/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
{% endif %}

Lessons/templates/includes/nav_bar.html
<nav class="navbar navbar-dark bg-primary fixed-top navbar-expand-lg font-weight-bold" style="background-color: #e3f2fd;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">LMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Students
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
            <li><a class="dropdown-item" href="{% url 'students:list' %}">List of students</a></li>
            <li><a class="dropdown-item" href="{% url 'students:create' %}">Add new student</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Teachers
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
            <li><a class="dropdown-item" href="{% url 'teachers:list' %}">List of teachers</a></li>
            <li><a class="dropdown-item" href="{% url 'teachers:create' %}">Add new teacher</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Groups
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
            <li><a class="dropdown-item" href="{% url 'groups:list' %}">List of groups</a></li>
            <li><a class="dropdown-item" href="{% url 'groups:create' %}">Create new group</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown4" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Courses
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown4">
            <li><a class="dropdown-item" href="{% url 'courses:list' %}">List of courses</a></li>
            <li><a class="dropdown-item" href="{% url 'courses:create' %}">Add new course</a></li>
          </ul>
        </li>

        <li class="nav-item">
          <li class="nav-item"><a class="nav-link" href="/contacts/" tabindex="-1">Contacts</a></li>
          <li class="nav-item"><a class="nav-link" href="/about/" tabindex="-1">About Us</a></li>
      </ul>
      <ul class="navbar-nav d-flex">
         <li class="nav-item dropdown">
           {% if user.is_authenticated %}
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             <img class="rounded-circle" width="40" height="40" src="{{ user.profile.avatar.url }}"> {{ user.username }}
           </a>
           <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
             <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign Out</a></li>
             <li><hr class="dropdown-divider"></li>
             <li><a class="dropdown-item" href="{% url 'accounts:profile_update' %}">Profile {{ user.username }}</a></li>
             <li><hr class="dropdown-divider"></li>
             <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password {{ user.username }}</a></li>
           {% else %}
             <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Sign In</a></li>
             <li><hr class="dropdown-divider"></li>
             <li><a class="dropdown-item" href="{% url 'accounts:registration' %}">Sign Up</a></li>
           {% endif %}
           </ul>
         </li>
       </ul>
      <form class="d-flex">
        <a class="btn btn-outline-success" data-bs-toggle="collapse" href="#collapseExample" role="button"
           aria-expanded="false" aria-controls="collapseExample">
            Search
        </a>
      </form>
    </div>
  </div>
</nav>

Lessons/templates/includes/paginator.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1{% if get_params %}&{{ get_params }}{% endif %}">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if get_params %}&{{ get_params }}{% endif %}">Previous</a></li>
      {% endif %}

      {% for page_num in page_obj.paginator.page_range %}
        {% if page_num == page_obj.number %}
            <li class="page-item active"><a class="page-link" href="?page={{ page_num }}{% if get_params %}&{{ get_params }}{% endif %}">{{ page_num }}</a></li>
        {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}{% if get_params %}&{{ get_params }}{% endif %}">{{ page_num }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if get_params %}&{{ get_params }}{% endif %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if get_params %}&{{ get_params }}{% endif %}">Last &raquo;</a></li>
      {% endif %}
  </ul>
</nav>

Lessons/templates/includes/students_list_table.html
<table class="table table-hover table-sm">
    <tr>
        <th>№</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Age</th>
        <th>Group</th>
        <th>Head man</th>
        <th>🖉</th>
        <th>🚮</th>
    </tr>
    {% for student in list_objects %}
        <tr>
            <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.age }}</td>
            <td>{% if student.group %}{{ student.group }}{% endif %}</td>
            <td>{% if student.headed_group %}{{ student.headed_group }}{% endif %}</td>
            <td><a href="{% url 'students:update' student.id %}">EDIT</a></td>
            <td><a href="{% url 'students:delete' student.id %}">DELETE</a></td>
        </tr>
    {% endfor %}
</table>

Lessons/templates/includes/teachers_list_table.html
<table class="table table-hover table-sm">
    <tr>
        <th>№</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Work experience</th>
        <th>Age</th>
        <th>Salary</th>
        <th>Group</th>
        <th>🖉</th>
        <th>🚮</th>
    </tr>
    {% for teacher in list_objects %}
        <tr>
            <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.email }}</td>
            <td>{{ teacher.work_experience }}</td>
            <td>{{ teacher.age }}</td>
            <td>{{ teacher.salary }}</td>
            <td>{% if teacher.group %}{{ teacher.group }}{% endif %}</td>
            <td><a href="{% url 'teachers:update' teacher.id %}">EDIT</a></td>
            <td><a href="{% url 'teachers:delete' teacher.id %}">DELETE</a></td>
        </tr>
    {% endfor %}
</table>