Lessons/groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', GroupDeleteView.as_view(), name='delete'),
]

Lessons/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lessons/students/urls.py
from django.urls import path

from students.views import StudentCreateView, StudentDeleteView, StudentUpdateView, StudentsListView

app_name = 'students'

urlpatterns = [
    path('', StudentsListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('update/<int:pk>/', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete'),
    # path('create/', create_student, name='create'),
    # path('update/<int:pk>/', update_student, name='update'),
    # path('update/<int:pk>/', UpdateStudentView.update_object, name='update'),
    # path('delete/<int:pk>/', delete_student, name='delete'),
]

Lessons/teachers/urls.py
from django.urls import path

from teachers.views import TeacherCreateView, TeacherDeleteView, TeacherUpdateView, TeachersListView

app_name = 'teachers'

urlpatterns = [
    path('', TeachersListView.as_view(), name='list'),
    path('create/', TeacherCreateView.as_view(), name='create'),
    path('update/<int:pk>/', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', TeacherDeleteView.as_view(), name='delete'),
    # path('', get_teachers, name='list'),
    # path('create/', create_teacher, name='create'),
    # path('update/<int:pk>/', update_teacher, name='update'),
    # path('delete/<int:pk>/', delete_teacher, name='delete'),
]

Lessons/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LMS -
        {% block title%}
            Home
        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <style>{% block custom_css %}{% endblock %}</style>
</head>
<body>
    {% include 'includes/nav_bar.html' %}


{#  {% block action %}#}
{#  {% endblock action %}#}

    <div class="container mt-4 pt-4">
    <div class="border rounder text-center p-3 m-3 mb-5 bg-light shadow">
        <h1>{% block header %}
            <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>Welcome to LMS!!!</strong></cite></span></h2>
            <hr />
        {% endblock %}</h1>
    </div>
    {% include 'includes/messages.html' %}
        {% block content %}

        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
</body>
</html>

Lessons/templates/flat_page.html
{% extends 'base.html' %}

{% block title %} {{ flatpage.title }} {% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>{{ flatpage.title }}</strong></cite></span></h2>
    <hr />
{% endblock%}

{% block content %}
    {{ flatpage.content }}
{% endblock %}

Lessons/templates/index.html
{% extends 'base.html' %}

{% block content %}
{#<a href="{%url 'students:list'%}"><h4>Students list</h4></a>#}
{##}
{#<a href="{%url 'teachers:list'%}"><h4>Teachers list</h4></a>#}
{##}
{#<a href="{%url 'groups:list'%}"><h4>Groups list</h4></a>#}
{% endblock %}