Lessons/groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', GroupDeleteView.as_view(), name='delete'),
]

Lessons/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lessons/groups/models.py
import datetime

from django.db import models

from teachers.models import Teacher

# from students.models import Student


class Group(models.Model):
    name = models.CharField(max_length=50)
    start_date = models.DateField(default=datetime.date.today)
    end_date = models.DateField(null=True, blank=True)
    headman = models.OneToOneField(
        # Student,
        'students.Student',
        on_delete=models.SET_NULL,
        null=True,
        related_name='headed_group'
    )

    teachers = models.ManyToManyField(
        to=Teacher,
        related_name='groups'
    )

    create_datetime = models.DateTimeField(auto_now_add=True)
    update_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

Lessons/groups/forms.py
from django.forms import ChoiceField, DateInput, ModelForm

from groups.models import Group


class GroupBaseForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'

        widgets = {'end_date': DateInput(attrs={'type': 'date'})}


class GroupCreateForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        exclude = ['end_date', 'headman']


class GroupUpdateForm(GroupBaseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['headman_field'] = ChoiceField(
            choices=[(st.id, str(st)) for st in self.instance.students.all()],
            label='Headman',
            required=False
        )

    class Meta(GroupBaseForm.Meta):
        exclude = ['headman']

Lessons/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from groups.forms import GroupCreateForm, GroupUpdateForm
from groups.models import Group

from students.models import Student


class GroupListView(LoginRequiredMixin, ListView):
    model = Group
    template_name = 'groups/list.html'
    paginate_by = 10


class GroupCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Group
    template_name = 'groups/create.html'
    form_class = GroupCreateForm
    success_url = reverse_lazy('groups:list')
    success_message = "%(name)s was created successfully"


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    template_name = 'groups/update.html'
    form_class = GroupUpdateForm
    success_url = reverse_lazy('groups:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.get_object().students.select_related('group', 'headed_group').all()

        return context

    def get_initial(self):
        initial = super().get_initial()
        try:
            initial['headman_field'] = self.object.headman.id
        except AttributeError as ex:  # noqa
            pass

        return initial

    def form_valid(self, form):
        response = super().form_valid(form)
        form.instance.headman = Student.objects.get(id=form.cleaned_data['headman_field'])
        form.instance.save()

        return response


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    template_name = 'groups/delete.html'
    success_url = reverse_lazy('groups:list')

Lessons/groups/templates/groups/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create group
{% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>Create group</strong></cite></span></h2>
    <hr />
{% endblock %}

{%block content%}
  <form method="post">
    {% csrf_token %}
    {{form | crispy}}
    <input class="btn btn-success" type="submit" value="Create">
    <a class="btn btn-primary" href="{% url 'groups:list' %}">Cancel</a>
  </form>
{%endblock%}

Lessons/groups/templates/groups/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete group
{% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>Delete group</strong></cite></span></h2>
    <hr />
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to remove {{ group.name }} ?</p>
        <input class="btn btn-danger" type="submit" value="Agree">
        <a class="btn btn-primary" href="{% url 'groups:list' %}">Cancel</a>
    </form>
{% endblock %}

Lessons/groups/templates/groups/list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>Groups list</strong></cite></span></h2>
    <hr />
{% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>List of groups</strong></cite></span></h2>
    <hr />
{% endblock %}

{% block content %}

{#    <p><strong>Count of groups: {{ object_list.count }}</strong></p>#}

    <table class="table table-hover table-sm">
        <tr>
            <th></th>
            <th>Group name</th>
            <th>Start data</th>
            <th>End data</th>
            <th>Head man</th>
            <th>Count students</th>
            <th><i class="bi bi-pencil-fill"></i></th>
            <th>🚮</th>
        </tr>
        {% for group in object_list %}
        <tr>
            <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
            <td>{{ group.name }}</td>
            <td>{{ group.start_date }}</td>
            <td>{% if group.end_date %}{{ group.end_date }}{% endif %}</td>
            <td>{% if group.headman %}{{ group.headman.last_name }} {{ group.headman.first_name }}{% endif %}</td>
            <td>{{ group.students.count }}</td>
            <td><a href="{% url 'groups:update' group.id %}">EDIT</a></td>
            <td><a href="{% url 'groups:delete' group.id %}">DELETE</a></td>
        </tr>
        {% endfor %}
    </table>

    {% include 'includes/paginator.html' %}

{% endblock %}

Lessons/groups/templates/groups/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Update group
{% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>Update group</strong></cite></span></h2>
    <hr />
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-success mt-3" type="submit" id="btn_save">Save</button>
        <a class="btn btn-primary mt-3" href="{% url 'groups:list' %}">Cancel</a>
    </form>
    {% with list_objects=students %}
        {% include 'includes/students_list_table.html' %}
    {% endwith %}

{% endblock %}