Lessons/courses/urls.py
from courses.views import CourseCreateView, CourseDeleteView, CourseUpdateView, CoursesListView

from django.urls import path

app_name = 'courses'

urlpatterns = [
    path('', CoursesListView.as_view(), name='list'),
    path('create/', CourseCreateView.as_view(), name='create'),
    path('update/<int:pk>/', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CourseDeleteView.as_view(), name='delete'),
]

Lessons/groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', GroupDeleteView.as_view(), name='delete'),
]

Lessons/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lessons/courses/models.py
import datetime

from django.db import models

from groups.models import Group


class Course(models.Model):
    name = models.CharField(max_length=50)
    start_date = models.DateField(default=datetime.date.today)
    end_date = models.DateField(null=True, blank=True)
    group = models.OneToOneField(
        Group,
        # 'groups.Group',
        on_delete=models.SET_NULL,
        null=True,
        related_name='courses'
    )

    def __str__(self):
        return self.name

Lessons/courses/forms.py
from courses.models import Course


from django.forms import DateInput, ModelForm


class CourseCreateForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        exclude = ['start_date']

        widgets = {'end_date': DateInput(attrs={'type': 'date'})}

Lessons/courses/views.py
from courses.forms import CourseCreateForm
from courses.models import Course

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView


class CoursesListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'courses/list.html'


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    template_name = 'courses/create.html'
    form_class = CourseCreateForm
    success_url = reverse_lazy('courses:list')


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    template_name = 'courses/update.html'
    form_class = CourseCreateForm
    success_url = reverse_lazy('courses:list')


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = 'courses/delete.html'
    success_url = reverse_lazy('courses:list')

Lessons/courses/templates/courses/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create course
{% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>Add new course</strong></cite></span></h2>
    <hr />
{% endblock %}

{%block content%}
  <form method="post">
    {% csrf_token %}
    {{form | crispy}}
    <input class="btn btn-success" type="submit" value="Create">
    <a class="btn btn-primary" href="{% url 'courses:list' %}">Cancel</a>
  </form>
{%endblock%}

Lessons/courses/templates/courses/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete course
{% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>Delete course</strong></cite></span></h2>
    <hr />
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to remove course {{ course.name }} ?</p>
        <input class="btn btn-danger" type="submit" value="Agree">
        <a class="btn btn-primary" href="{% url 'groups:list' %}">Cancel</a>
    </form>
{% endblock %}

Lessons/courses/templates/courses/list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Courses list
{% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>List of courses</strong></cite></span></h2>
    <hr />
{% endblock %}

{% block content %}

    <p><strong>Count of courses: {{ object_list.count }}</strong></p>

    <table class="table table-hover table-sm">
        <tr>
            <th>№</th>
            <th>Course name</th>
            <th>Start data</th>
            <th>End data</th>
            <th>🖉</th>
            <th>🚮</th>
        </tr>
        {% for course in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ course.name }}</td>
            <td>{{ course.start_date }}</td>
            <td>{{ course.end_date }}</td>
            <td><a href="{% url 'courses:update' course.id %}">EDIT</a></td>
            <td><a href="{% url 'courses:delete' course.id %}">DELETE</a></td>
        </tr>
        {% endfor %}

    </table>

{% endblock %}

Lessons/courses/templates/courses/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Update course
{% endblock %}

{% block header %}
    <h2 style="font-style:italic"><span style="color:#0033ff"><cite><strong>Update course</strong></cite></span></h2>
    <hr />
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-success mt-3" type="submit" id="btn_save">Save</button>
        <a class="btn btn-primary mt-3" href="{% url 'courses:list' %}">Cancel</a>
    </form>

{% endblock %}